### ISSUE TITLE
API routes return empty body when using sentry

### ISSUE THREAD

**Issue by topaxi** [sst/open-next#177] opened 2023-08-15 14:46 UTC
Adding `@sentry/nextjs` causes API routes to return an empty body.

Using SST 2.24.1 and Next.js 13.4.12 with Sentry 7.64.0

Reproduction repo: https://github.com/topaxi/empty-api-routes-sentry-sst

After deployment, navigate to `/api/hello` and the response body is empty (0 bytes)

Current workaround is to disable auto instrumentation of server functions (api routes, data fetching functions) via `autoInstrumentServerFunctions: false`.

**Comment by khuezy** [comment] 2023-08-16 02:00
@topaxi can you provide a sample code setup? I'm working on writing e2e tests and would be great to include this scenario in it.

**Comment by topaxi** [comment] 2023-08-16 07:07
Hi @khuezy thank you for your fast response! :) 

I have built a small reproduction repository and found out while doing so, that it's not actually the middleware causing it, but `@sentry/nextjs`.

I have linked to a reproduction repository in the original post.

**Comment by topaxi** [comment] 2023-08-16 07:10
There is probably something going wrong in the (automatic) instrumentation here: https://github.com/getsentry/sentry-javascript/blob/develop/packages/nextjs/src/common/wrapApiHandlerWithSentry.ts

Now I'm not sure which repo, open-next or sentry, is causing the issue. I'd be happy to report the issue over at sentry, if it is something that needs to be fixed there.

**Comment by caaatisgood** [comment] 2023-11-20 22:00
Hi there, are there any updates with this empty response issue? Or what's the best course of actions to diagnose the root cause? I'd like to dig into this problem as the product I'm working with needs Sentry to monitor the server-side errors.

**Comment by tsurumeso** [comment] 2024-03-06 18:47
@conico974 
Hi. I have a Next.js 12.3.4 project that works with OpenNext v2, but with OpenNext v3 (3.0.0-rc.6), I get an `Error: Cannot find module '. /cache.cjs'` when executing the Lambda function.
Is OpenNext v3 not compatible with Next.js 12?

**Comment by conico974** [comment] 2024-03-07 14:11
@tsurumeso It's a bug in V3 with next 12. 
We should change this line to something like a `require.resolve` to fix this issue.
I'll try to create a rc release that includes this fix by the end of the week

**Comment by conico974** [comment] 2024-03-11 15:32
@tsurumeso The  `Error: Cannot find module './cache.cjs'` issue should be fixed in `3.0.0-rc.7`. If you have other issues with next 12 and V3 you could create another issue or post something on the open-next discord channel https://discord.com/channels/983865673656705025/1027265626085019769

**Comment by tsurumeso** [comment] 2024-03-11 23:55
@conico974 
Thanks!

**Comment by conico974** [comment] 2024-05-03 18:43
Should be fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0)

**Closed by conico974** 2024-05-03 18:43 UTC
