### ISSUE TITLE
Headers function works differently in dev and production environments

### ISSUE THREAD

**Issue by Jack-Dane** [sst/open-next#360] opened 2024-02-10 13:28 UTC
I ran into this problem when deploying my app to production, the `headers()` function wasn't picking up a header that was added by middleware, but could get the value when running the application locally. 

I was adding the header to the response headers: 
```
export async function middleware(request: NextRequest) {
  let headers = new Headers(request.headers);
  headers.set("test-header", "abc");

  return NextResponse.next({
    headers: headers
  });
}
```
And is being read with: 
```
headers().get("test-header") || "could not find header 'test-header'"
```

The documentation mentions the function picks up request headers: 
> The headers function allows you to read the HTTP incoming request headers from a [Server Component](https://nextjs.org/docs/app/building-your-application/rendering/server-components).

https://nextjs.org/docs/app/api-reference/functions/headers

So I updated my middleware to add the header to request headers, which worked. But I would expect both environments to behave in the same way. It is not the case the middleware isn't working, based on the devtools network panel the response header is there, it just isn't being picked up the same way when developing. 

[Here is a reproducible example. ](https://github.com/Jack-Dane/headers-test-nextjs-sst)

Running in production. Deployed with `npx sst deploy --stage prod`. 
![Screenshot from 2024-02-07 20-38-12](https://github.com/sst/sst/assets/17383921/cea30698-c7ac-4f3f-9141-60f9376a9bf0)

Running on my machine as `npx sst dev` followed by `npm run dev`. 
![Screenshot from 2024-02-07 20-30-12](https://github.com/sst/sst/assets/17383921/e227d31a-9c44-4aa0-8930-acfeb5404484)

Package versions: 
```
jack@jackd:~/Documents/nextjs/headers-test$ npm list
headers-test@0.1.0 /home/jack/Documents/nextjs/headers-test
├── @types/node@20.11.16
├── @types/react-dom@18.2.18
├── @types/react@18.2.55
├── autoprefixer@10.4.17
├── aws-cdk-lib@2.124.0
├── constructs@10.3.0
├── eslint-config-next@14.1.0
├── eslint@8.56.0
├── next@14.1.0
├── postcss@8.4.34
├── react-dom@18.2.0
├── react@18.2.0
├── sst@2.40.1
├── tailwindcss@3.4.1
└── typescript@5.3.3
```

**Comment by conico974** [comment] 2024-02-12 15:21
Good catch, does it work this way with `next start` as well ? `next dev` doesn't exactly behave in the same way for a lot of things.

But honestly it almost feel like it is a bug in next itself (Not a big one but still), response headers should only apply to the response and not the request. As you said there is a `request.headers` field to pass headers to the request only.

Allowing this make it really easy to unintentionally leak some header that you might want to add only for your server.

**Comment by Jack-Dane** [comment] 2024-02-12 23:09
@conico974, thanks for the response, good point, I didn't try to see if it is a bug with Next. 

Both `npx next dev` and `npx next start` show the header. It makes me think the Next documentation might also be wrong because this header isn't in the network request.  
![Screenshot from 2024-02-12 23-03-46](https://github.com/sst/open-next/assets/17383921/1c86a6a4-23d2-43df-8d7b-6c4d07f92ad0)

> But honestly it almost feel like it is a bug in next itself (Not a big one but still), response headers should only apply to the response and not the request

I am not sure this is true (if I understand you correctly), it is not the case that the header is added to the request header by the middleware on an SST deployed application. It is added to the response header in both (which is expected) just the `headers` function seems to behaviour differently depending on the environment.

**Comment by conico974** [comment] 2024-02-13 20:45
It's normal that it does not appear on the network request, the middleware run after the request is sent.
I'm pretty sure that the problem is not in the `headers` function. This function just retrieve the request headers, nothing more, but they modify the request headers on the server itself.
You can pass headers to the request in an SST deployed app https://github.com/sst/open-next/blob/3deb2022d0bb506e4c4b66baeae248c7c2b153e5/examples/app-router/middleware.ts#L53-L58
There is even an e2e test to test it works, but it does use `request.headers`
Even in next docs they use `request.headers` to pass headers to the request https://nextjs.org/docs/app/building-your-application/routing/middleware#setting-headers

**Comment by conico974** [comment] 2024-05-03 18:23
Fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0)

**Closed by conico974** 2024-05-03 18:23 UTC
