### ISSUE TITLE
Sentry issue when using Next-Auth

### ISSUE THREAD

**Issue by leog** [sst/open-next#350] opened 2024-01-24 16:19 UTC
It seems there is a known issue when using Sentry with Next.js and packaged and deployed by SST.

Please follow through the following issue in the Sentry JS library repo: https://github.com/getsentry/sentry-javascript/issues/7797

The workaround that was effective for me was specifying `excludeServerRoutes: ['/api/auth/[...nextauth]']` as a Sentry config, but that also means any issue with Next-Auth will not be covered by Sentry, which is a major downside as anyone knows things can go wrong when it comes to authentication and following up issues using a tool such as Sentry is key to solve them.

**Comment by conico974** [comment] 2024-02-02 15:59
Duplicate of https://github.com/sst/open-next/issues/177
It is fixed in open-next V3 https://open-next.js.org/v3

**Comment by conico974** [comment] 2024-05-03 18:28
Should be fixed in [V3](https://github.com/sst/open-next/releases/tag/v3.0.0).
Feel free to reopen if the issue is still there

**Closed by conico974** 2024-05-03 18:28 UTC
Labels: duplicate

**Comment by digitaltoad** [comment] 2025-03-12 19:18
I'm working on a project where I'm still encountering this error. I'm using the newest version of SST and specifying to use the newest version of opennextjs. Unless I exclude the nextauth server routes, I'm seeing the `CLIENT_FETCH_ERROR` when fetching session, which ends up being an empty response. Is this possibly still related to opennext?

**Comment by conico974** [comment] 2025-03-12 21:03
@digitaltoad If there is an issue with OpenNext, you can create a new issue **with** a reproduction so that we could take a look.
